### ISSUE TITLE
Inceptionsdokument/Inceptionsfase

### ISSUE THREAD

**Issue by alhen18** [Diplom-Software2018/Anden-semester#25]
Dette dokument omkring Inceptionsfasen skal læses igennem:
[02 Inceptionsfasen](https://docs.google.com/document/d/15dTfnH5YqGPnBl8EhAm0raiRtLdFuQMohd7auYWS344/edit)

Her til skal der også kigges på den PowerPoint, som kan findes under:
Organisationsorienteret Softwareudvikling: Semesterprojekt ->
02 Inceptionsfasen: Udarbejdelse af inceptionsdokument -> Risici og Risikostyring inde på BlackBoard.
***
Opgave 1 og 3 er individuelle opgaver.
Opgave 2 og 4-7 er gruppe opgaver. 
***
# Opgave 1:
Genopfrisk din viden om problemorienteret projektarbejde.
Der skal ligges fokus på disse punkter:

- [04 Projektstart: Projektide og problemformulering](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5286959_1)
- [07 Skrivning og skriftlig formidling](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5332235_1)
- [08 Projektrapporten](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5343163_1)

***
# Opgave 2:
Dette er en check list til inceptions dokumentet:
[Lones Checkliste til inceptions dokumentet](https://docs.google.com/document/d/1ktLSuOYURHfrKI2HGcxCbIzczi4zFDvLD30BDxY41vk/edit)

- [x] Omslag.
    - [x] Projekttitle.
    - [x] Projektfase.
    - [x] Faseperiode.
    - [x] Vejleder. (Fornavn, Efternavn, SDU-mail)
    - [x] Projektgruppe nummer.
    - [x] Projekt medlemmer. (Fornavn, Efternavn, SDU-mail)
    - [x] Afleverings dato.
- [x] Indholdsfortegnelse.
- [x] Indledning.
    - [x] Historie og baggrund samt interesseparter.
    - [x] Problemformulering samt nødvendige spørgsmål.
    - [x] Formål og mål med inceptionsfasen.
- [x] Fremgangsmåde.
    - [x] Beskriv og begrund inceptionsfasen.
- [x] Business case. (resume)
    - [x] Resume af business case fra Organisation og ledelse (OL).
- [x] Forretningsområdet og eksisterende løsning.
    - [x] Beskrivelse af Forretningsområdet og eksisterende løsning.
- [x] Overordnet kravspecifikation.
    - [x] Brugsmønstermodel med afgræsning.
    - [x] Brugsmønsterdiagram.
    - [x] Aktørbeskrivelse.
    - [x] Brugsmønsterbeskrivelse.
    - [x] Beskrivelse af udvalgte og essentielle brugsmønster.
    - [x] Supplerende krav.
    - [x] Domænemodel med klassediagram.
    - [x] Beskrivelse af domænet og forretningbegreberne (klasserne)
- [x] Kritiske risici.
- [x] Tekniske gennemførlighed. (optionalt)
- [x] Prioritering.
- [x] Metode i elabrationsfasen.
    - [x] UP.
    - [x] Scrum.
    - [x] evt. selv udvalgte metoder.
- [x] Resurser.
- [x] Konklusion.
- [x] Bilag.
    - [x] Logbog.

### Omslag
Omslaget skal indeholde projekttitel, projektfase, faseperiode, vejleder, projektgruppe og projektdeltagere (fornavn, efternavn, sdu-email) samt afleverings dato.
### Indholdsfortegnelse
Læs selv det Lone har skrevet, for det er skrevet meget sjovt :D
"Er der en indholdsfortegnelse med højst to eller tre niveauer?"
### Indledning
Indledningen skal beskrive historien og baggrunden samt interesseparter. Den skal også indehold projektets problemformulering og de nødvendige spørgsmål til at besvar hovedspørgsmålet i problemformuleringen.
Indledningen skal beskrive formålet og målene med inceptionsfasen.
### Fremgangsmåde
Fremgangsmåden skal beskrive og begrunde fremgangsmåden for inceptionsfasen.
### Business case (resume)
Her henvises den business case som er udarbejdet som tællende aktivitet i Organisation og ledelse (OL).
Der skal skrives et resume af business cases som er blevet udarbejdet i OL.
### Forretningsområdet og eksisterende løsning
Det skal laves en beskrivelse af Forretningsområdet og eksisterende løsning.
### Overordnet kravspecifikation
Overordnet krav skal indenholde følgende:

1. Overordnet brugsmønstermodel med beskrivelse af afgrænsning

1. Brugsmønsterdiagram

1. Aktørbeskrivelse

1. Brugsmønsterbeskrivelse

1. Detaljeret beskrivelse af udvalgte, essentielle brugsmønstre

1. Overordnet beskrivelse af supplerende krav

1. Domænemodel med klasse diagram med en beskrivelse af domænet og forretningbegreberne (klasserne)

### Kritiske risici
Der er blevet identificeret nogle kritiske risici?
Hvis ja, give en beskrivelse af disse risici.
### Tekniske gennemførlighed (optionalt)
En undersøgelse af den tekniske gennemførlighed, dette er en punkt som bliver skrevet hvis tid til det.
### Prioritering
Bygger prioriteringen på kravenes forretningsmæssige betydning (nytte/benefit), arkitektoniske betydning, risiko samt læringsmæssige udbytte
### Metode i elabrationsfasen
En beskrives af de metoder som bliver brugt i elaborationsfasen, herunder skal der være en beskrives af UP og Scrum, samt en begrundelse og argumentation for valgte metoder.
### Resurser
Den aftalte arbejdstidsindsats uge for uge og alt i alt
### Konklusion
Konklusion på formål og mål i inceptionsfasen.
### Bilag
Der er medtaget et link til logbogen.
***
# Opgave 3:
Genopfrisk journaler fra GSE på første semester.
***
# Opgave 4:
Diskuter fremgangsmåden til inceptionsfasen.
Her skal der kombineres viden og metoder fra problemorienteret projektarbejde, GSE og inddrages resultater fra OL.
***
# Opgave 5:
Forbered og deltag i virksomheds møde.
### Forberedelse
Hver gruppe formulerer spørgsmål inden for gruppens afgrænsning med henblik på at få tilstrækkelige informationer til at gruppen kan gennemføre inceptionsfasen og udarbejde inceptionsdokumentet. En  måde at finde spørgsmålene på, er at lave udkast til især den overordnede brugsmønstermodel, men også til de øvrige afsnit i inceptionsdokumentet. Det vil afsløre hvilke oplysninger I mangler!
### Deltagelse
Alle projektgrupper deltager fuldtalligt. Spørgsmål til kunden bliver stillet af et panel bestående af en repræsentant fra hver af de deltagende projektgrupper. Hver projektgruppe klæder deres repræsentant på til at deltage i panelet og til at stille spørgsmål til kunden. I pauserne snakker repræsentanten med sin projektgruppe og bliver klædt på til næste runde. Grupperne må gerne skifte repræsentant undervejs.
***
# Opgave 6:
Udarbejd inceptionsdokument og gør klar til #26.
***
# Opgave 7:
Opdatere inceptionsdokumentet efter #26, som bliver en referance til #27

**Comment by stped18** [comment]
jeg laver et dokument på sigmul til i morgen

**Comment by stped18** [comment]
Lone har lavet et dokument der siger at vi har 7 opgaver til inceptionsfasen.
Kan der blive lavet issues på hver af dem?
