### ISSUE TITLE
(Inceptionsfasen) opgave 1: 

### ISSUE THREAD

**Issue by stped18** [Diplom-Software2018/Anden-semester#35]
### Opgave 1: Genopfrisk din viden om problemorienteret projektarbejde
Genopfrisk din viden om problemorienteret projektarbejde. Den relevante e-tivitet fra Online kurset i Problemorienteret projektarbejde er især

- 04  [Projektstart: Projektide og problemformulering med vægt på problemanalyse og projektgrundlag](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5286959_1)

men fordi I skal aflevere inceptionsdokumentet til bedømmelse så er disse også relevante: 

- 07 [Skrivning og skriftlig formidling](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5332235_1)
- 08 [Projektrapporten](https://e-learn.sdu.dk/webapps/blackboard/execute/displayLearningUnit?course_id=_394422_1&content_id=_5343163_1)

**Comment by alhen18** [comment]
Kig her: https://github.com/Diplom-Software2018/Anden-semester/issues/25
