### ISSUE TITLE
(Inceptionsfasen) opgave 2

### ISSUE THREAD

**Issue by stped18** [Diplom-Software2018/Anden-semester#36]
### Opgave 2: Studer kravene til inceptionsdokumentet
[Læs checkliste for inceptionsdokument.](https://docs.google.com/document/d/1ktLSuOYURHfrKI2HGcxCbIzczi4zFDvLD30BDxY41vk/edit)

**Comment by alhen18** [comment]
Kig her: https://github.com/Diplom-Software2018/Anden-semester/issues/25
