### ISSUE TITLE
Ændringer/omskrivning i Inceptionsdokument

### ISSUE THREAD

**Issue by aldus17** [Diplom-Software2018/Anden-semester#89]
Se eventuelt hvad der skal ændres/tilføjes udfra mødereferatet: https://docs.google.com/document/d/1upIMPtKZK3Xm2dCOkCwi_3OdBybdXOyE9PXameXDjF4/edit

**Comment by alhen18** [comment]
Der skal ikke skrives noget om på vores Inceptionsdokument, da det er afleveret og der skal være et bilag af det afleveret Inceptionsdokument i vores projekt rapport og ikke et bilag af et ændre Inceptionsdokument.
